FROM python:3.12-slim

RUN apt-get update \ 
    && apt-get install -y --no-install-recommends wget bzip2 \
    && apt-get clean

WORKDIR /opt/proptimus

COPY raphan.py .

RUN useradd --create-home --shell /bin/bash user \
    && chown -R user:user /opt \
    && chmod u+x raphan.py

USER user

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p $HOME/miniconda3 && \
    rm miniconda.sh

ENV PATH="/home/user/miniconda3/bin:${PATH}"

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main \
    && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r \
    && conda install -y -c conda-forge libgfortran=3.0.0 xtb=6.6.1 biopython=1.85 rdkit=2025.09.1 tqdm=4.67.1 \
    && conda clean -afy

CMD ["python3", "raphan.py"]
